version: '3'
services:
  app:
    image: registry.gitlab.com/khvalygin/tgvpn/dev:latest
    container_name: 'vpn-dev'
    ports:
      - '1194:1194/udp'
      - '8080:80/tcp'
    cap_add:
      - 'NET_ADMIN'
    environment:
      HOST_ADDR: '' # optional
    volumes:
      - openvpn-data:/opt/openvpn_data
      - openvpn-config:/etc/openvpn
volumes:
  openvpn-data:
    external: false
  openvpn-config:
    external: false